/*
 * lwagg_range_agg_bench.c
 *
 * Focused DAOS server-side lw-Agg range benchmark:
 *   - write N_OBJECTS large chunkwise objects, default 4096 x 1 MiB
 *   - each read aggregate fetches COUNT_PER_AGG 64 KiB ranges from
 *     COUNT_PER_AGG different large objects, default 16 x 64 KiB = 1 MiB
 *   - use the same DAOS aggregate recipe path as s3rdma_agg/lw-Agg:
 *       daos_set_nixl_agg_recipe(count, range_bs, LWAGG_FLAG|layer, start)
 *
 * The DAOS server must have DAOS_LWAGG_MANIFEST pointing to a manifest whose
 * third column is the source oid.lo list generated by this tool.
 */
#include <errno.h>
#include <inttypes.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>
#include <sys/syscall.h>
#include <sys/time.h>

#include <daos.h>
#include <daos_obj.h>
#include <daos/daos_nixl_req_id.h>

#include "../../src/plugins/obj/daos_direct/hashoid.h"

#define LWAGG_FLAG 0x80000000u

/* Some installed DAOS headers omit the public layout declarations even though
 * libdaos exports daos_obj_layout_get/free. Keep local declarations matching
 * DAOS src/include/daos/object.h so placement dumps use DAOS itself rather
 * than a reimplementation of the placement hash.
 */
struct lwagg_daos_shard_loc {
    uint32_t sd_rank;
    uint32_t sd_tgt_idx;
};

struct lwagg_daos_obj_shard {
    uint32_t os_replica_nr;
    struct lwagg_daos_shard_loc os_shard_loc[0];
};

struct lwagg_daos_obj_layout {
    uint32_t ol_ver;
    uint32_t ol_class;
    uint32_t ol_nr;
    struct lwagg_daos_obj_shard *ol_shards[0];
};

extern int daos_obj_layout_get(daos_handle_t coh, daos_obj_id_t oid,
                               struct lwagg_daos_obj_layout **layout);
extern int daos_obj_layout_free(struct lwagg_daos_obj_layout *layout);
extern uint64_t d_hash_murmur64(const unsigned char *key, unsigned int key_len,
                                unsigned int seed);
extern int obj_pl_grp_idx(uint32_t layout_gl_ver, uint64_t hash,
                          uint32_t grp_nr);

#define CHECK(rc) do { int _r = (rc); if (_r != 0) { \
    fprintf(stderr, "%s:%d failed rc=%d\n", __FILE__, __LINE__, _r); \
    exit(2); } } while (0)

static uint64_t now_us(void)
{
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (uint64_t)ts.tv_sec * 1000000ULL + ts.tv_nsec / 1000ULL;
}

static void client_trace_emit(FILE *fp, const char *event, int group,
                              uint64_t oid_hi, uint64_t oid_lo)
{
    if (!fp)
        return;
    struct timeval tv;
    gettimeofday(&tv, NULL);
    long tid = (long)syscall(SYS_gettid);
    fprintf(fp, "%ld.%06ld %ld %d %" PRIu64 ".%" PRIu64 " %s\n",
            (long)tv.tv_sec, (long)tv.tv_usec, tid, group,
            oid_hi, oid_lo, event);
}

static int ulcmp(const void *a, const void *b)
{
    unsigned long x = *(const unsigned long *)a;
    unsigned long y = *(const unsigned long *)b;
    return (x > y) - (x < y);
}

static unsigned char pat(int obj, int slice)
{
    return (unsigned char)((obj * 131 + slice * 17) & 0xff);
}

static int target_for_oid(daos_handle_t coh, uint64_t oid_lo, uint64_t oid_hi_user,
                          uint32_t *layout_nr_out, int *grp_idx_out)
{
    daos_obj_id_t oid = { .lo = oid_lo, .hi = oid_hi_user };
    CHECK(daos_obj_generate_oid(coh, &oid, DAOS_OT_MULTI_HASHED, OC_SX, 0, 0));

    struct lwagg_daos_obj_layout *layout = NULL;
    CHECK(daos_obj_layout_get(coh, oid, &layout));
    if (layout->ol_nr < 1 || layout->ol_shards[0]->os_replica_nr < 1) {
        fprintf(stderr, "empty layout for oid_lo=%" PRIu64 "\n", oid_lo);
        return -1;
    }

    uint64_t dkey_hash = d_hash_murmur64((const unsigned char *)"d", 1, 5731);
    int grp_idx = obj_pl_grp_idx(layout->ol_ver, dkey_hash, layout->ol_nr);
    if (grp_idx < 0 || (uint32_t)grp_idx >= layout->ol_nr) {
        fprintf(stderr, "bad grp_idx=%d layout_nr=%u for oid_lo=%" PRIu64 "\n",
                grp_idx, layout->ol_nr, oid_lo);
        daos_obj_layout_free(layout);
        return -1;
    }

    int target = (int)layout->ol_shards[grp_idx]->os_shard_loc[0].sd_tgt_idx;
    if (layout_nr_out)
        *layout_nr_out = layout->ol_nr;
    if (grp_idx_out)
        *grp_idx_out = grp_idx;
    daos_obj_layout_free(layout);
    return target;
}

static uint64_t *load_source_manifest_oid_los(const char *path, int n_expected)
{
    FILE *fp = fopen(path, "r");
    if (!fp) {
        perror(path);
        return NULL;
    }

    uint64_t *out = calloc((size_t)n_expected, sizeof(*out));
    if (!out) {
        fclose(fp);
        fprintf(stderr, "source oid list oom\n");
        return NULL;
    }

    char line[4096];
    int n = 0;
    while (fgets(line, sizeof(line), fp)) {
        if (line[0] == '#' || strncmp(line, "chunk_idx", 9) == 0)
            continue;
        char *save = NULL;
        char *tok = NULL;
        int col = 0;
        uint64_t oid_lo = 0;
        int have_oid = 0;
        for (tok = strtok_r(line, "\t\r\n", &save);
             tok != NULL;
             tok = strtok_r(NULL, "\t\r\n", &save), col++) {
            if (col == 2) {
                oid_lo = strtoull(tok, NULL, 10);
                have_oid = 1;
                break;
            }
        }
        if (!have_oid)
            continue;
        if (n >= n_expected) {
            fprintf(stderr, "source manifest %s has more than %d entries\n",
                    path, n_expected);
            free(out);
            fclose(fp);
            return NULL;
        }
        out[n++] = oid_lo;
    }
    fclose(fp);

    if (n != n_expected) {
        fprintf(stderr, "source manifest %s has %d entries; expected %d\n",
                path, n, n_expected);
        free(out);
        return NULL;
    }
    return out;
}

static void usage(const char *argv0)
{
    fprintf(stderr,
            "usage: %s <pool> <cont> <manifest_out> "
            "[N_OBJECTS=4096] [OBJECT_BYTES=1048576] [RANGE_BS=65536] "
            "[COUNT_PER_AGG=16] [PIPE=32] [SCRUB_MIB=512000] "
            "[SCRUB_CHUNK_MIB=64] [SCRUB_CONT=lwagg_range_scrub] "
            "[IOD_T=16] [IOD_I=4] [LAYER=0]\n",
            argv0);
}

int main(int argc, char **argv)
{
    if (argc < 4) {
        usage(argv[0]);
        return 1;
    }

    const char *pool = argv[1];
    const char *cont = argv[2];
    const char *manifest = argv[3];
    int n_objects     = argc > 4  ? atoi(argv[4])  : 4096;
    int object_bytes  = argc > 5  ? atoi(argv[5])  : 1048576;
    int range_bs      = argc > 6  ? atoi(argv[6])  : 65536;
    int count_per_agg = argc > 7  ? atoi(argv[7])  : 16;
    int pipe_depth    = argc > 8  ? atoi(argv[8])  : 32;
    long scrub_mib    = argc > 9  ? atol(argv[9])  : 512000;
    long scrub_c_mib  = argc > 10 ? atol(argv[10]) : 64;
    const char *scrub_cont = argc > 11 ? argv[11] : "lwagg_range_scrub";
    int iod_t         = argc > 12 ? atoi(argv[12]) : 16;
    int iod_i         = argc > 13 ? atoi(argv[13]) : 4;
    int layer         = argc > 14 ? atoi(argv[14]) : 0;

    if (n_objects <= 0 || object_bytes <= 0 || range_bs <= 0 ||
        count_per_agg <= 0 || pipe_depth <= 0 ||
        object_bytes % range_bs != 0 || n_objects % count_per_agg != 0) {
        usage(argv[0]);
        return 2;
    }

    int n_aggs = n_objects / count_per_agg;
    size_t agg_bytes = (size_t)count_per_agg * (size_t)range_bs;
    uint64_t layer_off = (uint64_t)layer * (uint64_t)range_bs;
    if (layer_off + (uint64_t)range_bs > (uint64_t)object_bytes) {
        fprintf(stderr, "layer range exceeds object size\n");
        return 2;
    }

    int skip_write = getenv("SKIP_WRITE") ? atoi(getenv("SKIP_WRITE")) : 0;
    int skip_scrub = getenv("SKIP_SCRUB") ? atoi(getenv("SKIP_SCRUB")) : 0;
    int skip_verify = getenv("SKIP_VERIFY") ? atoi(getenv("SKIP_VERIFY")) : 1;
    int skip_read = getenv("SKIP_READ") ? atoi(getenv("SKIP_READ")) : 0;
    int rr_placement = getenv("RR_TARGET_PLACEMENT") ? atoi(getenv("RR_TARGET_PLACEMENT")) : 0;
    int rr_targets = getenv("RR_TARGETS") ? atoi(getenv("RR_TARGETS")) : 8;
    const char *dump_placement = getenv("DUMP_PLACEMENT");
    const char *source_manifest = getenv("SOURCE_MANIFEST");
    const char *client_trace_path = getenv("CLIENT_TRACE");
    FILE *client_trace = NULL;
    if (client_trace_path && client_trace_path[0] != '\0') {
        client_trace = fopen(client_trace_path, "w");
        if (!client_trace) {
            perror(client_trace_path);
            return 2;
        }
        setvbuf(client_trace, NULL, _IOLBF, 0);
    }

    printf("lwagg_range_agg_bench\n");
    printf("  pool/cont       : %s / %s\n", pool, cont);
    printf("  objects         : %d x %d B (%.2f GiB)\n",
           n_objects, object_bytes,
           (double)n_objects * object_bytes / 1073741824.0);
    printf("  range           : layer=%d off=%" PRIu64 " len=%d\n",
           layer, layer_off, range_bs);
    printf("  aggregate       : %d ranges x %d B = %.2f MiB\n",
           count_per_agg, range_bs, (double)agg_bytes / 1048576.0);
    printf("  requests        : %d aggregate RPCs, PIPE=%d\n", n_aggs, pipe_depth);
    printf("  manifest        : %s\n", manifest);
    printf("  recipe IOD      : T=%d IOD=%d object_bytes_for_hi=%d\n",
           iod_t, iod_i, object_bytes);
    printf("  placement       : %s%s\n", rr_placement ? "round-robin target" : "sequential oid",
           rr_placement ? "" : "");
    printf("  source manifest : %s\n",
           (source_manifest && source_manifest[0]) ? source_manifest : "(pattern fill)");

    CHECK(daos_init());
    daos_handle_t poh = DAOS_HDL_INVAL;
    daos_handle_t coh = DAOS_HDL_INVAL;
    CHECK(daos_pool_connect(pool, NULL, DAOS_PC_RW, &poh, NULL, NULL));

    int rc = daos_cont_create_with_label(poh, cont, NULL, NULL, NULL);
    if (rc != 0 && rc != -DER_EXIST) CHECK(rc);
    CHECK(daos_cont_open(poh, cont, DAOS_COO_RW, &coh, NULL, NULL));

    uint64_t *oid_los = calloc((size_t)n_objects, sizeof(*oid_los));
    if (!oid_los) {
        fprintf(stderr, "oid_los oom\n");
        return 2;
    }
    uint64_t base_lo = hashoid_layer_base(0);
    uint64_t oid_hi_user = hashoid_oid_hi_user(iod_t, iod_i, object_bytes);
    if (rr_targets <= 0 || rr_targets > 64) {
        fprintf(stderr, "RR_TARGETS must be in [1, 64]\n");
        return 2;
    }
    if (!rr_placement) {
        for (int i = 0; i < n_objects; ++i)
            oid_los[i] = base_lo + (uint64_t)i;
    } else {
        printf("[RR] selecting oid_lo values for local round-robin target placement...\n");
        uint64_t candidate = base_lo;
        for (int i = 0; i < n_objects; ++i) {
            int desired = i % rr_targets;
            for (;;) {
                int target = target_for_oid(coh, candidate, oid_hi_user, NULL, NULL);
                if (target < 0)
                    return 2;
                if (target == desired) {
                    oid_los[i] = candidate++;
                    break;
                }
                candidate++;
            }
            if ((i + 1) % 512 == 0)
                printf("  [RR] %d/%d selected, next_candidate=%" PRIu64 "\n",
                       i + 1, n_objects, candidate - base_lo);
        }
    }
    {
        daos_obj_id_t oid = { .lo = oid_los[0], .hi = oid_hi_user };
        CHECK(daos_obj_generate_oid(coh, &oid, DAOS_OT_MULTI_HASHED, OC_SX, 0, 0));
    }

    daos_obj_id_t first_oid = { .lo = oid_los[0], .hi = oid_hi_user };
    CHECK(daos_obj_generate_oid(coh, &first_oid, DAOS_OT_MULTI_HASHED, OC_SX, 0, 0));
    uint64_t oid_hi_full = first_oid.hi;

    FILE *mf = fopen(manifest, "w");
    if (!mf) {
        perror(manifest);
        return 2;
    }
    fprintf(mf, "chunk_idx\tkey\toid_lo\toid_hi_user\toid_hi_full\n");
    for (int i = 0; i < n_objects; ++i)
        fprintf(mf, "%d\tlwagg_range_%05d\t%" PRIu64 "\t%" PRIu64 "\t%" PRIu64 "\n",
                i, i, oid_los[i], oid_hi_user, oid_hi_full);
    fclose(mf);

    if (dump_placement && dump_placement[0] != '\0') {
        FILE *pf = fopen(dump_placement, "w");
        if (!pf) {
            perror(dump_placement);
            return 2;
        }
        fprintf(pf, "chunk_idx,group,oid_hi,oid_lo,layout_nr,grp_idx,rank,target\n");
        int group_hist[8] = {0};
        int global_hist[8] = {0};
        int max_group = 0;
        int skewed_groups = 0;
        for (int i = 0; i < n_objects; ++i) {
            daos_obj_id_t oid = { .lo = oid_los[i], .hi = oid_hi_user };
            CHECK(daos_obj_generate_oid(coh, &oid, DAOS_OT_MULTI_HASHED, OC_SX, 0, 0));
            struct lwagg_daos_obj_layout *layout = NULL;
            CHECK(daos_obj_layout_get(coh, oid, &layout));
            if (layout->ol_nr < 1 || layout->ol_shards[0]->os_replica_nr < 1) {
                fprintf(stderr, "empty layout for object %d\n", i);
                return 2;
            }
            uint64_t dkey_hash = d_hash_murmur64((const unsigned char *)"d", 1, 5731);
            int grp_idx = obj_pl_grp_idx(layout->ol_ver, dkey_hash, layout->ol_nr);
            if (grp_idx < 0 || (uint32_t)grp_idx >= layout->ol_nr) {
                fprintf(stderr, "bad grp_idx=%d layout_nr=%u for object %d\n",
                        grp_idx, layout->ol_nr, i);
                return 2;
            }
            uint32_t rank = layout->ol_shards[grp_idx]->os_shard_loc[0].sd_rank;
            uint32_t tgt = layout->ol_shards[grp_idx]->os_shard_loc[0].sd_tgt_idx;
            fprintf(pf, "%d,%d,%" PRIu64 ",%" PRIu64 ",%u,%d,%u,%u\n",
                    i, i / count_per_agg, oid.hi, oid.lo, layout->ol_nr,
                    grp_idx, rank, tgt);
            if (tgt < 8) {
                group_hist[tgt]++;
                global_hist[tgt]++;
            }
            daos_obj_layout_free(layout);

            if ((i + 1) % count_per_agg == 0) {
                int gmax = 0;
                int nonzero = 0;
                for (int t = 0; t < 8; ++t) {
                    if (group_hist[t] > gmax)
                        gmax = group_hist[t];
                    if (group_hist[t] > 0)
                        nonzero++;
                }
                if (gmax > max_group)
                    max_group = gmax;
                if (gmax > 3 || nonzero < 6)
                    skewed_groups++;
                memset(group_hist, 0, sizeof(group_hist));
            }
        }
        fclose(pf);
        printf("[PLACEMENT] wrote %s\n", dump_placement);
        printf("[PLACEMENT] global target counts:");
        for (int t = 0; t < 8; ++t)
            printf(" t%d=%d", t, global_hist[t]);
        printf("\n");
        printf("[PLACEMENT] group max_count max=%d skewed_groups=%d/%d\n",
               max_group, skewed_groups, n_aggs);
    }

    daos_key_t dk;
    d_iov_set(&dk, (void *)"d", 1);

    uint64_t *source_oid_los = NULL;
    if (source_manifest && source_manifest[0] != '\0') {
        source_oid_los = load_source_manifest_oid_los(source_manifest, n_objects);
        if (!source_oid_los)
            return 2;
    }

    if (!skip_write) {
        printf("[WRITE] writing large source objects%s...\n",
               source_oid_los ? " by copying source manifest" : "");
        char *buf = aligned_alloc(4096, (size_t)object_bytes);
        if (!buf) {
            fprintf(stderr, "write buf oom\n");
            return 2;
        }
        uint64_t tw0 = now_us();
        for (int i = 0; i < n_objects; ++i) {
            if (source_oid_los) {
                daos_obj_id_t src_oid = { .lo = source_oid_los[i],
                                          .hi = oid_hi_user };
                CHECK(daos_obj_generate_oid(coh, &src_oid, DAOS_OT_MULTI_HASHED,
                                            OC_SX, 0, 0));
                daos_handle_t src_oh = DAOS_HDL_INVAL;
                CHECK(daos_obj_open(coh, src_oid, DAOS_OO_RO, &src_oh, NULL));
                d_iov_t src_iov;
                d_iov_set(&src_iov, buf, (size_t)object_bytes);
                d_sg_list_t src_sgl = {
                    .sg_nr = 1, .sg_nr_out = 1, .sg_iovs = &src_iov
                };
                daos_recx_t src_rx = {
                    .rx_idx = 0, .rx_nr = (uint64_t)object_bytes
                };
                daos_iod_t src_iod = {0};
                d_iov_set(&src_iod.iod_name, (void *)"a", 1);
                src_iod.iod_type = DAOS_IOD_ARRAY;
                src_iod.iod_size = 1;
                src_iod.iod_nr = 1;
                src_iod.iod_recxs = &src_rx;
                CHECK(daos_obj_fetch(src_oh, DAOS_TX_NONE, 0, &dk, 1,
                                     &src_iod, &src_sgl, NULL, NULL));
                CHECK(daos_obj_close(src_oh, NULL));
            } else {
                for (int off = 0, slice = 0;
                     off < object_bytes;
                     off += range_bs, ++slice)
                    memset(buf + off, pat(i, slice), (size_t)range_bs);
            }

            daos_obj_id_t oid = { .lo = oid_los[i], .hi = oid_hi_user };
            CHECK(daos_obj_generate_oid(coh, &oid, DAOS_OT_MULTI_HASHED, OC_SX, 0, 0));
            daos_handle_t oh = DAOS_HDL_INVAL;
            CHECK(daos_obj_open(coh, oid, DAOS_OO_RW, &oh, NULL));
            d_iov_t iov;
            d_iov_set(&iov, buf, (size_t)object_bytes);
            d_sg_list_t sgl = { .sg_nr = 1, .sg_nr_out = 1, .sg_iovs = &iov };
            daos_recx_t rx = { .rx_idx = 0, .rx_nr = (uint64_t)object_bytes };
            daos_iod_t iod = {0};
            d_iov_set(&iod.iod_name, (void *)"a", 1);
            iod.iod_type = DAOS_IOD_ARRAY;
            iod.iod_size = 1;
            iod.iod_nr = 1;
            iod.iod_recxs = &rx;
            CHECK(daos_obj_update(oh, DAOS_TX_NONE, 0, &dk, 1, &iod, &sgl, NULL));
            CHECK(daos_obj_close(oh, NULL));
            if ((i + 1) % 512 == 0)
                printf("  [WRITE] %d/%d\n", i + 1, n_objects);
        }
        uint64_t tw1 = now_us();
        printf("[WRITE] done: %.2f GiB in %.2f s (%.2f GB/s)\n",
               (double)n_objects * object_bytes / 1073741824.0,
               (double)(tw1 - tw0) / 1e6,
               (double)n_objects * object_bytes / (double)(tw1 - tw0) / 1e3);
        free(buf);
    } else {
        printf("[WRITE] SKIPPED\n");
    }
    free(source_oid_los);

    daos_handle_t coh_scrub = DAOS_HDL_INVAL;
    if (!skip_scrub && scrub_mib > 0) {
        rc = daos_cont_create_with_label(poh, scrub_cont, NULL, NULL, NULL);
        if (rc != 0 && rc != -DER_EXIST) CHECK(rc);
        CHECK(daos_cont_open(poh, scrub_cont, DAOS_COO_RW, &coh_scrub, NULL, NULL));

        size_t scrub_chunk = (size_t)scrub_c_mib * 1048576ULL;
        long scrub_iter = ((size_t)scrub_mib * 1048576ULL) / scrub_chunk;
        char *sbuf = aligned_alloc(4096, scrub_chunk);
        if (!sbuf) {
            fprintf(stderr, "scrub buf oom\n");
            return 2;
        }
        memset(sbuf, 0xa5, scrub_chunk);
        printf("[SCRUB] %ld x %ld MiB = %ld MiB...\n",
               scrub_iter, scrub_c_mib, scrub_mib);
        uint64_t ts0 = now_us();
        for (long i = 0; i < scrub_iter; ++i) {
            daos_obj_id_t oid = { .lo = 0xD00D000000ULL + (uint64_t)i, .hi = 0 };
            CHECK(daos_obj_generate_oid(coh_scrub, &oid, DAOS_OT_MULTI_HASHED, OC_SX, 0, 0));
            daos_handle_t oh = DAOS_HDL_INVAL;
            CHECK(daos_obj_open(coh_scrub, oid, DAOS_OO_RW, &oh, NULL));
            d_iov_t iov;
            d_iov_set(&iov, sbuf, scrub_chunk);
            d_sg_list_t sgl = { .sg_nr = 1, .sg_nr_out = 1, .sg_iovs = &iov };
            daos_recx_t rx = { .rx_idx = 0, .rx_nr = scrub_chunk };
            daos_iod_t iod = {0};
            d_iov_set(&iod.iod_name, (void *)"a", 1);
            iod.iod_type = DAOS_IOD_ARRAY;
            iod.iod_size = 1;
            iod.iod_nr = 1;
            iod.iod_recxs = &rx;
            CHECK(daos_obj_update(oh, DAOS_TX_NONE, 0, &dk, 1, &iod, &sgl, NULL));
            CHECK(daos_obj_close(oh, NULL));
            if ((i + 1) % 128 == 0) {
                uint64_t tsx = now_us();
                printf("  [SCRUB] %ld/%ld (%.2f GB/s)\n", i + 1, scrub_iter,
                       (double)(i + 1) * scrub_chunk / (double)(tsx - ts0) / 1e3);
            }
        }
        uint64_t ts1 = now_us();
        printf("[SCRUB] done in %.2f s (%.2f GB/s)\n",
               (double)(ts1 - ts0) / 1e6,
               (double)scrub_iter * scrub_chunk / (double)(ts1 - ts0) / 1e3);
        free(sbuf);
    } else {
        printf("[SCRUB] SKIPPED\n");
    }

    if (skip_read) {
        printf("[READ] SKIPPED\n");
        if (coh_scrub.cookie != 0) {
            daos_cont_close(coh_scrub, NULL);
            daos_cont_destroy(poh, scrub_cont, 1, NULL);
        }
        daos_cont_close(coh, NULL);
        daos_pool_disconnect(poh, NULL);
        daos_fini();
        free(oid_los);
        return 0;
    }

    daos_handle_t *oh_cache = calloc((size_t)n_aggs, sizeof(*oh_cache));
    if (!oh_cache) {
        fprintf(stderr, "oh_cache oom\n");
        return 2;
    }
    for (int g = 0; g < n_aggs; ++g) {
        daos_obj_id_t agg_oid = {
            .lo = base_lo + (uint64_t)(g * count_per_agg),
            .hi = oid_hi_user,
        };
        CHECK(daos_obj_generate_oid(coh, &agg_oid, DAOS_OT_MULTI_HASHED, OC_SX, 0, 0));
        CHECK(daos_obj_open(coh, agg_oid, DAOS_OO_RO, &oh_cache[g], NULL));
    }

    typedef struct slot {
        daos_event_t ev;
        int group;
        char *buf;
        daos_iod_t iod;
        daos_recx_t recx;
        d_iov_t *iovs;
        d_sg_list_t sgl;
        uint64_t submit_us;
    } slot_t;

    daos_handle_t eqh = DAOS_HDL_INVAL;
    CHECK(daos_eq_create(&eqh));
    slot_t *slots = calloc((size_t)pipe_depth, sizeof(*slots));
    unsigned long *lat = calloc((size_t)n_aggs, sizeof(*lat));
    if (!slots || !lat) {
        fprintf(stderr, "slot/lat oom\n");
        return 2;
    }
    for (int s = 0; s < pipe_depth; ++s) {
        slots[s].buf = aligned_alloc(4096, agg_bytes);
        slots[s].iovs = calloc((size_t)count_per_agg, sizeof(d_iov_t));
        if (!slots[s].buf || !slots[s].iovs) {
            fprintf(stderr, "slot data oom\n");
            return 2;
        }
        slots[s].group = -1;
        CHECK(daos_event_init(&slots[s].ev, eqh, NULL));
    }

    printf("[READ] %d aggregate RPCs, PIPE=%d, logical bytes=%.2f MiB...\n",
           n_aggs, pipe_depth, (double)n_aggs * agg_bytes / 1048576.0);

    int next = 0;
    int done = 0;
    int bad = 0;
    uint64_t tr0 = now_us();

    while (next < n_aggs && next < pipe_depth) {
        slot_t *s = &slots[next];
        s->group = next;
        memset(s->buf, 0xee, agg_bytes);
        for (int k = 0; k < count_per_agg; ++k)
            d_iov_set(&s->iovs[k], s->buf + (size_t)k * range_bs, (size_t)range_bs);
        s->sgl.sg_nr = count_per_agg;
        s->sgl.sg_nr_out = count_per_agg;
        s->sgl.sg_iovs = s->iovs;
        s->recx.rx_idx = 0;
        s->recx.rx_nr = (uint64_t)agg_bytes;
        memset(&s->iod, 0, sizeof(s->iod));
        d_iov_set(&s->iod.iod_name, (void *)"a", 1);
        s->iod.iod_type = DAOS_IOD_ARRAY;
        s->iod.iod_size = 1;
        s->iod.iod_nr = 1;
        s->iod.iod_recxs = &s->recx;
        uint32_t layer_recipe = LWAGG_FLAG | (uint32_t)layer;
        daos_set_nixl_agg_recipe((uint32_t)count_per_agg, (uint32_t)range_bs,
                                  layer_recipe, (uint32_t)(next * count_per_agg));
        uint64_t synthetic_lo = base_lo + (uint64_t)(next * count_per_agg);
        client_trace_emit(client_trace, "client_submit", next,
                          oid_hi_full, synthetic_lo);
        s->submit_us = now_us();
        CHECK(daos_obj_fetch(oh_cache[next], DAOS_TX_NONE, 0, &dk, 1,
                             &s->iod, &s->sgl, NULL, &s->ev));
        client_trace_emit(client_trace, "client_posted", next,
                          oid_hi_full, synthetic_lo);
        daos_set_nixl_agg_recipe(0, 0, 0, 0);
        next++;
    }

    while (done < n_aggs) {
        daos_event_t *evs[pipe_depth];
        int n = daos_eq_poll(eqh, 0, DAOS_EQ_WAIT, pipe_depth, evs);
        if (n < 0) CHECK(n);
        for (int i = 0; i < n; ++i) {
            slot_t *s = NULL;
            for (int k = 0; k < pipe_depth; ++k) {
                if (&slots[k].ev == evs[i]) {
                    s = &slots[k];
                    break;
                }
            }
            if (!s) {
                fprintf(stderr, "event->slot mismatch\n");
                return 2;
            }
            if (evs[i]->ev_error != 0) {
                fprintf(stderr, "group=%d ev_error=%d\n", s->group, evs[i]->ev_error);
                return 2;
            }
            uint64_t td = now_us();
            lat[s->group] = (unsigned long)(td - s->submit_us);
            uint64_t synthetic_lo = base_lo + (uint64_t)(s->group * count_per_agg);
            client_trace_emit(client_trace, "client_complete", s->group,
                              oid_hi_full, synthetic_lo);
            if (!skip_verify) {
                int base = s->group * count_per_agg;
                int slice = (int)(layer_off / (uint64_t)range_bs);
                for (int k = 0; k < count_per_agg; ++k) {
                    unsigned char got = (unsigned char)s->buf[(size_t)k * range_bs];
                    unsigned char want = pat(base + k, slice);
                    if (got != want)
                        bad++;
                }
            }

            CHECK(daos_event_fini(evs[i]));
            CHECK(daos_event_init(evs[i], eqh, NULL));
            done++;

            if (next < n_aggs) {
                int g = next++;
                s->group = g;
                memset(s->buf, 0xee, agg_bytes);
                for (int k = 0; k < count_per_agg; ++k)
                    d_iov_set(&s->iovs[k], s->buf + (size_t)k * range_bs, (size_t)range_bs);
                s->sgl.sg_nr = count_per_agg;
                s->sgl.sg_nr_out = count_per_agg;
                s->sgl.sg_iovs = s->iovs;
                s->recx.rx_idx = 0;
                s->recx.rx_nr = (uint64_t)agg_bytes;
                memset(&s->iod, 0, sizeof(s->iod));
                d_iov_set(&s->iod.iod_name, (void *)"a", 1);
                s->iod.iod_type = DAOS_IOD_ARRAY;
                s->iod.iod_size = 1;
                s->iod.iod_nr = 1;
                s->iod.iod_recxs = &s->recx;
                uint32_t layer_recipe = LWAGG_FLAG | (uint32_t)layer;
                daos_set_nixl_agg_recipe((uint32_t)count_per_agg, (uint32_t)range_bs,
                                          layer_recipe, (uint32_t)(g * count_per_agg));
                uint64_t synthetic_lo = base_lo + (uint64_t)(g * count_per_agg);
                client_trace_emit(client_trace, "client_submit", g,
                                  oid_hi_full, synthetic_lo);
                s->submit_us = now_us();
                CHECK(daos_obj_fetch(oh_cache[g], DAOS_TX_NONE, 0, &dk, 1,
                                     &s->iod, &s->sgl, NULL, &s->ev));
                client_trace_emit(client_trace, "client_posted", g,
                                  oid_hi_full, synthetic_lo);
                daos_set_nixl_agg_recipe(0, 0, 0, 0);
            }
        }
    }
    uint64_t tr1 = now_us();

    qsort(lat, (size_t)n_aggs, sizeof(*lat), ulcmp);
    double sum = 0.0;
    for (int i = 0; i < n_aggs; ++i)
        sum += (double)lat[i];
    unsigned long p50 = lat[n_aggs / 2];
    unsigned long p99 = lat[(n_aggs * 99) / 100];
    double mean = sum / n_aggs;
    double logical_gb = (double)n_aggs * agg_bytes / 1e9;

    printf("\n=== LWAGG RANGE AGG RESULTS ===\n");
    printf("Aggregate RPCs:     %d\n", n_aggs);
    printf("Bytes/RPC:          %zu (%.2f MiB)\n", agg_bytes, (double)agg_bytes / 1048576.0);
    printf("Logical bytes:      %.3f GB\n", logical_gb);
    printf("Wall time:          %.2f ms\n", (double)(tr1 - tr0) / 1000.0);
    printf("Throughput:         %.2f GB/s\n", logical_gb / ((double)(tr1 - tr0) / 1e6));
    printf("Per-RPC lat us:     min=%lu p50=%lu p99=%lu max=%lu mean=%.1f\n",
           lat[0], p50, p99, lat[n_aggs - 1], mean);
    printf("Verify mismatches:  %d\n", bad);

    for (int s = 0; s < pipe_depth; ++s) {
        daos_event_fini(&slots[s].ev);
        free(slots[s].buf);
        free(slots[s].iovs);
    }
    free(slots);
    daos_eq_destroy(eqh, 0);
    for (int g = 0; g < n_aggs; ++g)
        daos_obj_close(oh_cache[g], NULL);
    free(oh_cache);
    free(lat);
    free(oid_los);

    if (coh_scrub.cookie != 0) {
        daos_cont_close(coh_scrub, NULL);
        daos_cont_destroy(poh, scrub_cont, 1, NULL);
    }
    daos_cont_close(coh, NULL);
    daos_pool_disconnect(poh, NULL);
    daos_fini();
    if (client_trace)
        fclose(client_trace);
    return bad ? 3 : 0;
}
